-- USERS tábla létrehozása
CREATE TABLE USERS
(
    USER_ID int PRIMARY KEY,
    USER_NAME varchar(20),
    USER_PASSWORD varchar2(64),
    USER_ROLE varchar(10)
);
CREATE UNIQUE INDEX USERS_USER_ID_uindex ON USERS (USER_ID);

-- PRODUCT_GROUPS tábla létrehozása
CREATE TABLE PRODUCT_GROUPS
(
    PRODUCT_GROUP_ID int PRIMARY KEY,
    PRODUCT_GROUP_NAME varchar(20)
);
CREATE UNIQUE INDEX PRODUCT_GROUPS_PRODUCT_GROUP_ID_uindex ON PRODUCT_GROUPS (PRODUCT_GROUP_ID);

-- PRODUCTS tábla létrehozása
CREATE TABLE PRODUCTS
(
    PRODUCT_NAME VARCHAR(20) PRIMARY KEY,
    PRODUCT_TYPE varchar(10),
    PRODUCT_GROUP_ID int,
    QUANTITY_IN_STOCK int,
    CONSTRAINT FK_GROUP_ID FOREIGN KEY (PRODUCT_GROUP_ID) REFERENCES PRODUCT_GROUPS (PRODUCT_GROUP_ID) ON DELETE CASCADE ON UPDATE CASCADE
);

-- REQUESTS tábla létrehozása
CREATE TABLE REQUESTS
(
    REQUEST_ID int PRIMARY KEY,
    OWNER_ID int,
    PRODUCT_NAME varchar(20),
    ORDERED_AMOUNT int,
    CONSTRAINT FK_OWNER_ID FOREIGN KEY (OWNER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX REQUESTS_REQUEST_ID_uindex ON REQUESTS (REQUEST_ID);

-- NEW_ITEM_REQUESTS tábla létrehozása
CREATE TABLE NEW_ITEM_REQUESTS
(
    NEW_ITEM_ID int PRIMARY KEY,
    PRODUCT_NAME varchar(20),
    USER_ID int,
    CONSTRAINT FK_NEW_ITEM_OWNER FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID) ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX NEW_ITEM_REQUESTS_NEW_ITEM_ID_uindex ON NEW_ITEM_REQUESTS (NEW_ITEM_ID);