CREATE TABLE USER
(
    ID int PRIMARY KEY,
    USERNAME varchar2(20),
    PASSWORD varchar2(100),
    ROLE varchar2(10)
);
CREATE UNIQUE INDEX USER_ID_uindex ON USER (ID);

CREATE TABLE REQUEST
(
    ID int PRIMARY KEY,
    OWNER int,
    PRODUCTNAME varchar2(20),
    QUANTITY int
);
CREATE UNIQUE INDEX REQUEST_ID_uindex ON REQUEST (ID);

CREATE TABLE PRODUCT
(
    PRODUCTNAME varchar2(20) PRIMARY KEY,
    TYPE varchar2(20),
    GROUP_ID int,
    QUANTITY int
);
CREATE UNIQUE INDEX PRODUCT_PRODUCTNAME_uindex ON PRODUCT (PRODUCTNAME);

CREATE TABLE PRODUCT_GROUP
(
    ID int PRIMARY KEY,
    GROUPNAME varchar2(10)
);
CREATE UNIQUE INDEX PRODUCT_GROUP_ID_uindex ON PRODUCT_GROUP (ID);

CREATE TABLE NEW_ITEM_REQUEST
(
    ID int PRIMARY KEY,
    PRODUCTNAME varchar2(20),
    OWNER int
);
CREATE UNIQUE INDEX NEW_ITEM_REQUEST_ID_uindex ON NEW_ITEM_REQUEST (ID);